/*
 * Copyright (c) NeoForged and contributors
 * SPDX-License-Identifier: LGPL-2.1-only
 */

package net.neoforged.bus;

import net.neoforged.bus.api.EventListener;
import org.jetbrains.annotations.ApiStatus;

/**
 * Base class for event listeners generated by {@link EventListenerFactory}.
 */
@ApiStatus.Internal
public abstract non-sealed class GeneratedEventListener extends EventListener {}
