/*
 * Copyright (c) NeoForged and contributors
 * SPDX-License-Identifier: LGPL-2.1-only
 */

package net.neoforged.bus;

import net.neoforged.bus.api.EventListener;

/**
 * Base class for event listeners generated by {@link EventListenerFactory}.
 */
public abstract non-sealed class GeneratedEventListener extends EventListener {
}
